[package]
name = "hash_file"
version = "0.1.0"
authors = ["Nicolas Osborne <nicolas.osborne.etu@univ-lille.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.0-alpha.2"

